// +build !ignore_autogenerated

/*
Copyright (C) MongoDB, Inc. 2020-present.

Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License. You may obtain
a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package dbaas

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionInfo) DeepCopyInto(out *ConnectionInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionInfo.
func (in *ConnectionInfo) DeepCopy() *ConnectionInfo {
	if in == nil {
		return nil
	}
	out := new(ConnectionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseProvider) DeepCopyInto(out *DatabaseProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseProvider.
func (in *DatabaseProvider) DeepCopy() *DatabaseProvider {
	if in == nil {
		return nil
	}
	out := new(DatabaseProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instance) DeepCopyInto(out *Instance) {
	*out = *in
	out.InstanceInfo = in.InstanceInfo
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instance.
func (in *Instance) DeepCopy() *Instance {
	if in == nil {
		return nil
	}
	out := new(Instance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceInfo) DeepCopyInto(out *InstanceInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceInfo.
func (in *InstanceInfo) DeepCopy() *InstanceInfo {
	if in == nil {
		return nil
	}
	out := new(InstanceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAtlasConnection) DeepCopyInto(out *MongoDBAtlasConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAtlasConnection.
func (in *MongoDBAtlasConnection) DeepCopy() *MongoDBAtlasConnection {
	if in == nil {
		return nil
	}
	out := new(MongoDBAtlasConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBAtlasConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAtlasConnectionList) DeepCopyInto(out *MongoDBAtlasConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MongoDBAtlasConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAtlasConnectionList.
func (in *MongoDBAtlasConnectionList) DeepCopy() *MongoDBAtlasConnectionList {
	if in == nil {
		return nil
	}
	out := new(MongoDBAtlasConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBAtlasConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAtlasConnectionSpec) DeepCopyInto(out *MongoDBAtlasConnectionSpec) {
	*out = *in
	if in.ConnectionRef != nil {
		in, out := &in.ConnectionRef, &out.ConnectionRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAtlasConnectionSpec.
func (in *MongoDBAtlasConnectionSpec) DeepCopy() *MongoDBAtlasConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(MongoDBAtlasConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAtlasConnectionStatus) DeepCopyInto(out *MongoDBAtlasConnectionStatus) {
	*out = *in
	in.Common.DeepCopyInto(&out.Common)
	if in.CredentialsRef != nil {
		in, out := &in.CredentialsRef, &out.CredentialsRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	out.ConnectionInfo = in.ConnectionInfo
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAtlasConnectionStatus.
func (in *MongoDBAtlasConnectionStatus) DeepCopy() *MongoDBAtlasConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(MongoDBAtlasConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAtlasInventory) DeepCopyInto(out *MongoDBAtlasInventory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAtlasInventory.
func (in *MongoDBAtlasInventory) DeepCopy() *MongoDBAtlasInventory {
	if in == nil {
		return nil
	}
	out := new(MongoDBAtlasInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBAtlasInventory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAtlasInventoryList) DeepCopyInto(out *MongoDBAtlasInventoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MongoDBAtlasInventory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAtlasInventoryList.
func (in *MongoDBAtlasInventoryList) DeepCopy() *MongoDBAtlasInventoryList {
	if in == nil {
		return nil
	}
	out := new(MongoDBAtlasInventoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBAtlasInventoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAtlasInventoryProviderSpec) DeepCopyInto(out *MongoDBAtlasInventoryProviderSpec) {
	*out = *in
	if in.CredentialsRef != nil {
		in, out := &in.CredentialsRef, &out.CredentialsRef
		*out = new(NamespacedName)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAtlasInventoryProviderSpec.
func (in *MongoDBAtlasInventoryProviderSpec) DeepCopy() *MongoDBAtlasInventoryProviderSpec {
	if in == nil {
		return nil
	}
	out := new(MongoDBAtlasInventoryProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAtlasInventorySpec) DeepCopyInto(out *MongoDBAtlasInventorySpec) {
	*out = *in
	out.Provider = in.Provider
	in.MongoDBAtlasInventoryProviderSpec.DeepCopyInto(&out.MongoDBAtlasInventoryProviderSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAtlasInventorySpec.
func (in *MongoDBAtlasInventorySpec) DeepCopy() *MongoDBAtlasInventorySpec {
	if in == nil {
		return nil
	}
	out := new(MongoDBAtlasInventorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAtlasInventoryStatus) DeepCopyInto(out *MongoDBAtlasInventoryStatus) {
	*out = *in
	in.Common.DeepCopyInto(&out.Common)
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]Instance, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAtlasInventoryStatus.
func (in *MongoDBAtlasInventoryStatus) DeepCopy() *MongoDBAtlasInventoryStatus {
	if in == nil {
		return nil
	}
	out := new(MongoDBAtlasInventoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedName) DeepCopyInto(out *NamespacedName) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedName.
func (in *NamespacedName) DeepCopy() *NamespacedName {
	if in == nil {
		return nil
	}
	out := new(NamespacedName)
	in.DeepCopyInto(out)
	return out
}
